In [29]:
#################################################
#created the 24/04/2018 12:57 by Alexis Blanchet#
#################################################
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET
PATH = '/home/alexis/Bureau/Stage/ProgrammesTV/pluri_201712/2017-12-01_programmeTV/IPTV_0192_2017-12-01_TF1.xml'

In [30]:
import xmltodict, json
from xml.dom import minidom 
tree = ET.parse(PATH).getroot()
xmlstr = ET.tostring(tree)
o = xmltodict.parse(xmlstr)
L = json.dumps(o) 
with open('data.txt', 'w') as outfile:
    json.dump(L, outfile)

In [31]:
tree = ET.parse(PATH)
root = tree.getroot()
#print(root.tag)
l1 = [child for child in root]
#print(l1)
l2 = [[child for child in root] for root in l1 ]
print(l2[1])

for i,elem in enumerate(l2[1]):
    xmlstr = ET.tostring(elem)
    o = xmltodict.parse(xmlstr)
    with open('data'+str(i)+'.txt', 'w') as outfile:
        json.dump(o, outfile)

[<Element 'DIFFUSION' at 0x7f54d7e14778>, <Element 'DIFFUSION' at 0x7f54d7e77b88>, <Element 'DIFFUSION' at 0x7f54d7e84818>, <Element 'DIFFUSION' at 0x7f54d8063728>, <Element 'DIFFUSION' at 0x7f54d806d3b8>, <Element 'DIFFUSION' at 0x7f54d7e2b458>, <Element 'DIFFUSION' at 0x7f54d7e2e4f8>, <Element 'DIFFUSION' at 0x7f54d7e339a8>, <Element 'DIFFUSION' at 0x7f54d7db7818>, <Element 'DIFFUSION' at 0x7f54d7db8778>, <Element 'DIFFUSION' at 0x7f54d7dbd688>, <Element 'DIFFUSION' at 0x7f54d7dc26d8>, <Element 'DIFFUSION' at 0x7f54d7dc54a8>, <Element 'DIFFUSION' at 0x7f54d7dc9408>, <Element 'DIFFUSION' at 0x7f54d7dcd098>, <Element 'DIFFUSION' at 0x7f54d7dd2e58>, <Element 'DIFFUSION' at 0x7f54d7ddbcc8>, <Element 'DIFFUSION' at 0x7f54d7de09f8>, <Element 'DIFFUSION' at 0x7f54d7de4908>, <Element 'DIFFUSION' at 0x7f54d7defe08>, <Element 'DIFFUSION' at 0x7f54d7df2a98>, <Element 'DIFFUSION' at 0x7f54d7d76868>, <Element 'DIFFUSION' at 0x7f54d7d7a4a8>, <Element 'DIFFUSION' at 0x7f54d7d7d138>, <Element 'DIFFUSION' at 0x7f54d7d80ef8>, <Element 'DIFFUSION' at 0x7f54d7d85ef8>, <Element 'DIFFUSION' at 0x7f54d7d8e4f8>, <Element 'DIFFUSION' at 0x7f54d7d91368>, <Element 'DIFFUSION' at 0x7f54d7d95098>]

In [53]:
data = pd.DataFrame()
for i in range(29):
    temp_data = pd.read_json('data'+str(i)+'.txt')
    temp_data = temp_data.rename(columns={"DIFFUSION": i})
    df = [data,temp_data]
    data = pd.concat(df,axis=1)

In [54]:
data = data.T
data
data.to_csv('IPTV_0192_2017-12-01_TF1.csv')

In [61]:
data = pd.read_csv('IPTV_0192_2017-12-01_TF1.csv',index_col=0)
data.shape

(29, 8)

In [62]:
temp_data = pd.DataFrame()   
for i in range(29):    
    df = data['ATTRIBUTS']
    l = (df[[i]].values)[0]
    df2 = pd.DataFrame.from_dict(eval(l),orient = 'index')
    df2 = df2.rename(columns = {0: i})
    #print(df2.head())
    temp_data = [temp_data,df2]
    temp_data = pd.concat(temp_data,axis = 1)
temp_data.head()

      0  1  2  3  4  5  6  7  8  9  ... 19 20 21 22 23 24 25 26 27 28
PT1    0  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  1  0  0  0
PT2    0  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  1  0  0
PT3    0  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  1
CLAIR  0  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
DOLBY  0  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0

[5 rows x 29 columns]

In [64]:
data = data.join(temp_data.T,how='left')
data

,@CLEDIF,@DATEMODIF,ATTRIBUTS,CSA,DATEHEURE,DUREE,EMISSION,TITRE,PT1,PT2,...,DIFFERE,RESUME,PREMDIF,DERDIF,REDIF,INEDIT_EN_CLAIR,INEDIT_CRYPTE,NOUVEAUTE,TEMPSFORT,OCCULTATIONMOBILE
0,167439753,2017-11-08T02:12:33,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T06:25:00,120,"{'@CLEEMI': '122835453', '@DATEMODIF': '2017-1...",TFou,0,0,...,0,0,0,0,0,1,0,0,0,0
1,167439754,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T08:25:00,5,"{'@CLEEMI': '122842665', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,0,0,0,0,0,0,0,0,0,0
2,167439755,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T08:30:00,45,"{'@CLEEMI': '122842666', '@DATEMODIF': '2017-1...",TÃ©lÃ©shopping,0,0,...,0,0,0,0,0,0,0,0,0,0
3,167439756,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:15:00,5,"{'@CLEEMI': '122842667', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,0,0,0,0,0,0,0,0,0,0
4,167439757,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:20:00,30,"{'@CLEEMI': '116093509', '@DATEMODIF': '2017-1...",Petits secrets entre voisins,0,0,...,0,0,0,0,1,0,0,0,0,0
5,167439758,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:50:00,35,"{'@CLEEMI': '116093509', '@DATEMODIF': '2017-1...",Petits secrets entre voisins,0,0,...,0,0,0,0,1,0,0,0,0,0
6,167439759,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T10:25:00,35,"{'@CLEEMI': '122835415', '@DATEMODIF': '2017-1...",Demain nous appartient,0,0,...,0,0,0,0,1,0,0,0,0,0
7,167439760,2017-11-18T03:16:26,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T11:00:00,55,"{'@CLEEMI': '120971283', '@DATEMODIF': '2017-1...",Les feux de l'amour,0,0,...,0,0,0,0,0,1,0,0,0,0
8,167439761,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T11:55:00,5,"{'@CLEEMI': '122842668', '@DATEMODIF': '2017-1...",Petits plats en Ã©quilibre,0,0,...,0,0,0,0,0,0,0,0,0,0
9,167439762,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T12:00:00,55,"{'@CLEEMI': '122842669', '@DATEMODIF': '2017-1...",Les douze coups de midi,0,0,...,0,0,0,0,0,0,0,0,0,0
10,167439763,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T12:55:00,5,"{'@CLEEMI': '122842670', '@DATEMODIF': '2017-1...",L'affiche du jour,0,0,...,0,0,0,0,0,0,0,0,0,0
11,167439764,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:00:00,30,"{'@CLEEMI': '122842959', '@DATEMODIF': '2017-1...",Journal,0,0,...,0,0,0,0,0,0,0,0,0,0
12,167439765,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:30:00,10,"{'@CLEEMI': '122842671', '@DATEMODIF': '2017-1...",Petits plats en Ã©quilibre,0,0,...,0,0,0,0,0,0,0,0,0,0
13,167439766,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:40:00,15,"{'@CLEEMI': '122842672', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,0,0,0,0,0,0,0,0,0,0
14,167439767,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:55:00,105,"{'@CLEEMI': '111248282', '@DATEMODIF': '2017-1...",En cavale pour NoÃ«l,0,0,...,0,0,0,0,0,0,0,0,0,0
15,167439768,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T15:40:00,90,"{'@CLEEMI': '71508277', '@DATEMODIF': '2016-12...",MariÃ© avant NoÃ«l,0,0,...,0,0,0,0,0,0,0,0,0,0
16,167439769,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T17:10:00,65,"{'@CLEEMI': '122842673', '@DATEMODIF': '2017-1...",Quatre mariages pour une lune de miel,0,0,...,0,0,0,0,0,0,0,0,0,0
17,167439770,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T18:15:00,65,"{'@CLEEMI': '122843237', '@DATEMODIF': '2017-1...",Mon plus beau NoÃ«l,0,0,...,0,0,0,0,0,0,0,0,0,0
18,167439771,2017-11-18T03:16:52,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T19:20:00,35,"{'@CLEEMI': '122835416', '@DATEMODIF': '2017-1...",Demain nous appartient,0,0,...,0,0,0,0,0,1,0,0,0,0
19,167439772,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T19:55:00,5,"{'@CLEEMI': '122842674', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,0,0,0,0,0,0,0,0,0,0
20,167439773,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:00:00,35,"{'@CLEEMI': '122842950', '@DATEMODIF': '2017-1...",Journal,0,0,...,0,0,0,0,0,0,0,0,0,0
21,167439774,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:35:00,5,"{'@CLEEMI': '122842675', '@DATEMODIF': '2017-1...",My Million,0,0,...,0,0,0,0,0,0,0,0,0,0
22,167439775,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:40:00,5,"{'@CLEEMI': '122842676', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,0,0,0,0,0,0,0,0,0,0
23,167439776,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:45:00,5,"{'@CLEEMI': '122843067', '@DATEMODIF': '2017-1...",Nos chers voisins,0,0,...,0,0,0,0,0,0,0,0,0,0
24,167439777,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:50:00,10,"{'@CLEEMI': '122842677', '@DATEMODIF': '2017-1...",C'est Canteloup,0,0,...,0,0,0,0,0,0,0,0,0,0
25,167437456,2017-11-18T03:16:58,"{'PT1': '1', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T21:00:00,150,"{'@CLEEMI': '122841996', '@DATEMODIF': '2017-1...",EnfoirÃ©s Kids,1,0,...,0,0,0,0,0,1,0,0,0,0
26,167437457,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '1', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T23:30:00,125,"{'@CLEEMI': '122842004', '@DATEMODIF': '2017-1...","Vendredi, tout est permis avec Arthur",0,1,...,0,0,0,0,0,0,0,0,0,0
27,167439778,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-02T01:35:00,5,"{'@CLEEMI': '122842678', '@DATEMODIF': '2017-1...",Tirage de l'Euro Millions,0,0,...,0,0,0,0,0,0,0,0,0,0
28,167439779,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '1', 'CLAIR': ...",0,2017-12-02T01:40:00,290,"{'@CLEEMI': '108980346', '@DATEMODIF': '2017-1...",Programmes de la nuit,0,0,...,0,0,0,0,1,0,0,0,0,0

In [66]:
temp_data = pd.DataFrame()   
for i in range(29):    
    df = data['EMISSION']
    l = (df[[i]].values)[0]
    df2 = pd.DataFrame.from_dict(eval(l),orient = 'index')
    df2 = df2.rename(columns = {0: i})
    #print(df2.head())
    temp_data = [temp_data,df2]
    temp_data = pd.concat(temp_data,axis = 1)
    temp_data = temp_data.drop(['@DATEMODIF'])
temp_data.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
@CLEEMI,122835453,122842665,122842666,122842667,116093509,116093509,122835415,120971283,122842668,122842669,...,122842674,122842950,122842675,122842676,122843067,122842677,122841996,122842004,122842678,108980346
CS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,{'LIEUENREGISTREMENT': 'Ã l'ArÃ©na du Pays d'Ai...,NaN,NaN,NaN
FILMTELEFILM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FORMAT,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '4', '#text': 'Feuilleton'}","{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '16', '#text': 'Autre'}",...,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '7', '#text': 'Concert'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '16', '#text': 'Autre'}"
GENRE,"{'@CLE': '403', '@GENRESIMPLE': 'Magazine jeun...","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...","{'@CLE': '425', '@GENRESIMPLE': 'Magazine de s...","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...","{'@CLE': '969', '@GENRESIMPLE': 'SÃ©rie dramati...","{'@CLE': '50', '@GENRESIMPLE': 'SÃ©rie sentimen...","{'@CLE': '397', '@GENRESIMPLE': 'Magazine de l...","{'@CLE': '950', '@GENRESIMPLE': 'Jeu', '#text'...",...,"{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...","{'@CLE': '952', '@GENRESIMPLE': 'Journal', '#t...","{'@CLE': '421', '@GENRESIMPLE': 'Magazine de s...","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...","{'@CLE': '31', '@GENRESIMPLE': 'SÃ©rie humorist...","{'@CLE': '957', '@GENRESIMPLE': 'Divertissemen...","{'@CLE': '75', '@GENRESIMPLE': 'Concert', '#te...","{'@CLE': '932', '@GENRESIMPLE': 'Divertissemen...","{'@CLE': '1083', '@GENRESIMPLE': 'Jeu', '#text...","{'@CLE': '1057', '@GENRESIMPLE': 'Programme in..."

In [67]:
data = data.join(temp_data.T)

,@CLEDIF,@DATEMODIF,ATTRIBUTS,CSA,DATEHEURE,DUREE,EMISSION,TITRE,PT1,PT2,...,FILMTELEFILM,FORMAT,GENRE,LESPERSONNES,LESTEXTES,MAGAZINEXY,NATIONALITE,PHOTO,SERIE,TITREEMISSION
0,167439753,2017-11-08T02:12:33,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T06:25:00,120,"{'@CLEEMI': '122835453', '@DATEMODIF': '2017-1...",TFou,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '403', '@GENRESIMPLE': 'Magazine jeun...",NaN,"{'TEXTE': [{'@TYPE': '0', 'LETEXTE': 'Au somma...","{'COLLECTION': {'@CLE': '6999', 'TYPECOLLECTIO...",NaN,IPTV_C122835453.jpg,NaN,TFou
1,167439754,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T08:25:00,5,"{'@CLEEMI': '122842665', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842665.jpg,NaN,MÃ©tÃ©o
2,167439755,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T08:30:00,45,"{'@CLEEMI': '122842666', '@DATEMODIF': '2017-1...",TÃ©lÃ©shopping,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '425', '@GENRESIMPLE': 'Magazine de s...","{'PERSONNE': [{'@CLE': '120137', 'FONCTION': '...",NaN,"{'COLLECTION': {'@CLE': '6986', 'TYPECOLLECTIO...",NaN,IPTV_C122842666.jpg,NaN,TÃ©lÃ©shopping
3,167439756,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:15:00,5,"{'@CLEEMI': '122842667', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842667.jpg,NaN,MÃ©tÃ©o
4,167439757,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:20:00,30,"{'@CLEEMI': '116093509', '@DATEMODIF': '2017-1...",Petits secrets entre voisins,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...",NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins
5,167439758,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T09:50:00,35,"{'@CLEEMI': '116093509', '@DATEMODIF': '2017-1...",Petits secrets entre voisins,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...",NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins
6,167439759,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T10:25:00,35,"{'@CLEEMI': '122835415', '@DATEMODIF': '2017-1...",Demain nous appartient,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '969', '@GENRESIMPLE': 'SÃ©rie dramati...","{'PERSONNE': [{'@CLE': '159285', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Maxime ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122835415.jpg,"{'COLLECTION': [{'@CLE': '26743151', 'TYPECOLL...",Demain nous appartient
7,167439760,2017-11-18T03:16:26,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T11:00:00,55,"{'@CLEEMI': '120971283', '@DATEMODIF': '2017-1...",Les feux de l'amour,0,0,...,NaN,"{'@CLE': '4', '#text': 'Feuilleton'}","{'@CLE': '50', '@GENRESIMPLE': 'SÃ©rie sentimen...","{'PERSONNE': [{'@CLE': '262561', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Jack es...",NaN,"{'@CLE': '7', 'PAYS': 'Etats-Unis', 'LIBELLE':...",IPTV_C120971283.jpg,"{'COLLECTION': [{'@CLE': '6475', 'TYPECOLLECTI...",Les feux de l'amour
8,167439761,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T11:55:00,5,"{'@CLEEMI': '122842668', '@DATEMODIF': '2017-1...",Petits plats en Ã©quilibre,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '397', '@GENRESIMPLE': 'Magazine de l...","{'PERSONNE': {'@CLE': '122485', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Toutes le...","{'COLLECTION': {'@CLE': '3166156', 'TYPECOLLEC...",NaN,IPTV_C122842668.jpg,NaN,Petits plats en Ã©quilibre
9,167439762,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T12:00:00,55,"{'@CLEEMI': '122842669', '@DATEMODIF': '2017-1...",Les douze coups de midi,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '950', '@GENRESIMPLE': 'Jeu', '#text'...","{'PERSONNE': {'@CLE': '125961', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Chaque jo...","{'COLLECTION': {'@CLE': '4188704', 'TYPECOLLEC...",NaN,IPTV_C122842669.jpg,NaN,Les douze coups de midi
10,167439763,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T12:55:00,5,"{'@CLEEMI': '122842670', '@DATEMODIF': '2017-1...",L'affiche du jour,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '424', '@GENRESIMPLE': 'Magazine spor...","{'PERSONNE': [{'@CLE': '600066', 'FONCTION': '...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Un consul...","{'COLLECTION': {'@CLE': '3201344', 'TYPECOLLEC...",NaN,IPTV_C122842670.jpg,NaN,L'affiche du jour
11,167439764,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:00:00,30,"{'@CLEEMI': '122842959', '@DATEMODIF': '2017-1...",Journal,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '952', '@GENRESIMPLE': 'Journal', '#t...","{'PERSONNE': {'@CLE': '120966', 'FONCTION': 'P...",NaN,"{'COLLECTION': {'@CLE': '8310', 'TYPECOLLECTIO...",NaN,IPTV_C122842959.jpg,NaN,Journal
12,167439765,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:30:00,10,"{'@CLEEMI': '122842671', '@DATEMODIF': '2017-1...",Petits plats en Ã©quilibre,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '397', '@GENRESIMPLE': 'Magazine de l...","{'PERSONNE': {'@CLE': '122485', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Toutes le...","{'COLLECTION': {'@CLE': '3166156', 'TYPECOLLEC...",NaN,IPTV_C122842671.jpg,NaN,Petits plats en Ã©quilibre
13,167439766,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:40:00,15,"{'@CLEEMI': '122842672', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842672.jpg,NaN,MÃ©tÃ©o
14,167439767,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T13:55:00,105,"{'@CLEEMI': '111248282', '@DATEMODIF': '2017-1...",En cavale pour NoÃ«l,0,0,...,{'TITREORIGINAL': 'Debbie Macomber's Dashing T...,"{'@CLE': '2', '#text': 'TÃ©lÃ©film'}","{'@CLE': '340', '@GENRESIMPLE': 'TÃ©lÃ©film mÃ©lo...","{'PERSONNE': [{'@CLE': '14104', 'FONCTION': 'R...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'AprÃ¨s ...",NaN,"{'@CLE': '155', 'PAYS': 'Canada', 'LIBELLE': '...",IPTV_E111248282.jpg,NaN,En cavale pour NoÃ«l
15,167439768,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T15:40:00,90,"{'@CLEEMI': '71508277', '@DATEMODIF': '2016-12...",MariÃ© avant NoÃ«l,0,0,...,"{'TITREORIGINAL': 'A Bride for Christmas', 'AN...","{'@CLE': '2', '#text': 'TÃ©lÃ©film'}","{'@CLE': '340', '@GENRESIMPLE': 'TÃ©lÃ©film mÃ©lo...","{'PERSONNE': [{'@CLE': '488065', 'FONCTION': '...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'Deux c...",NaN,"{'@CLE': '16', 'PAYS': 'Etats-Unis - Canada', ...",IPTV_E71508277.jpg,NaN,MariÃ© avant NoÃ«l
16,167439769,2017-11-07T12:08:12,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T17:10:00,65,"{'@CLEEMI': '122842673', '@DATEMODIF': '2017-1...",Quatre mariages pour une lune de miel,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '967', '@GENRESIMPLE': 'TÃ©lÃ©rÃ©alitÃ©',...",NaN,"{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Quatre je...","{'COLLECTION': {'@CLE': '6774593', 'TYPECOLLEC...",NaN,IPTV_C122842673.jpg,NaN,Quatre mariages pour une lune de miel
17,167439770,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T18:15:00,65,"{'@CLEEMI': '122843237', '@DATEMODIF': '2017-1...",Mon plus beau NoÃ«l,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '967', '@GENRESIMPLE': 'TÃ©lÃ©rÃ©alitÃ©',...","{'PERSONNE': {'@CLE': '365103', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Quatre fa...","{'COLLECTION': {'@CLE': '28892992', 'TYPECOLLE...",NaN,IPTV_C122843237.jpg,NaN,Mon plus beau NoÃ«l
18,167439771,2017-11-18T03:16:52,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T19:20:00,35,"{'@CLEEMI': '122835416', '@DATEMODIF': '2017-1...",Demain nous appartient,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '969', '@GENRESIMPLE': 'SÃ©rie dramati...","{'PERSONNE': [{'@CLE': '159285', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Rafael ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122835416.jpg,"{'COLLECTION': [{'@CLE': '26743151', 'TYPECOLL...",Demain nous appartient
19,167439772,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T19:55:00,5,"{'@CLEEMI': '122842674', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842674.jpg,NaN,MÃ©tÃ©o
20,167439773,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:00:00,35,"{'@CLEEMI': '122842950', '@DATEMODIF': '2017-1...",Journal,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '952', '@GENRESIMPLE': 'Journal', '#t...","{'PERSONNE': {'@CLE': '333079', 'FONCTION': 'P...",NaN,"{'COLLECTION': {'@CLE': '8310', 'TYPECOLLECTIO...",NaN,IPTV_C122842950.jpg,NaN,Journal
21,167439774,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:35:00,5,"{'@CLEEMI': '122842675', '@DATEMODIF': '2017-1...",My Million,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '421', '@GENRESIMPLE': 'Magazine de s...",NaN,NaN,"{'COLLECTION': {'@CLE': '12577694', 'TYPECOLLE...",NaN,IPTV_C122842675.jpg,NaN,My Million
22,167439775,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:40:00,5,"{'@CLEEMI': '122842676', '@DATEMODIF': '2017-1...",MÃ©tÃ©o,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842676.jpg,NaN,MÃ©tÃ©o
23,167439776,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:45:00,5,"{'@CLEEMI': '122843067', '@DATEMODIF': '2017-1...",Nos chers voisins,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '31', '@GENRESIMPLE': 'SÃ©rie humorist...","{'PERSONNE': [{'@CLE': '2006', 'FONCTION': 'Ac...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'ProblÃ¨...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122843067.jpg,"{'COLLECTION': [{'@CLE': '8555721', 'TYPECOLLE...",Nos chers voisins
24,167439777,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T20:50:00,10,"{'@CLEEMI': '122842677', '@DATEMODIF': '2017-1...",C'est Canteloup,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '957', '@GENRESIMPLE': 'Divertissemen...","{'PERSONNE': [{'@CLE': '142528', 'FONCTION': '...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'DÃ©tournem...","{'COLLECTION': {'@CLE': '11736233', 'TYPECOLLE...",NaN,IPTV_C122842677.jpg,NaN,C'est Canteloup
25,167437456,2017-11-18T03:16:58,"{'PT1': '1', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T21:00:00,150,"{'@CLEEMI': '122841996', '@DATEMODIF': '2017-1...",EnfoirÃ©s Kids,1,0,...,NaN,"{'@CLE': '7', '#text': 'Concert'}","{'@CLE': '75', '@GENRESIMPLE': 'Concert', '#te...","{'PERSONNE': [{'@CLE': '1340672', 'FONCTION': ...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Sur la ...",NaN,NaN,IPTV_E122841996.jpg,NaN,EnfoirÃ©s Kids
26,167437457,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '1', 'PT3': '0', 'CLAIR': ...",1,2017-12-01T23:30:00,125,"{'@CLEEMI': '122842004', '@DATEMODIF': '2017-1...","Vendredi, tout est permis avec Arthur",0,1,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '932', '@GENRESIMPLE': 'Divertissemen...","{'PERSONNE': {'@CLE': '9021', 'FONCTION': 'PrÃ©...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Comme tou...","{'COLLECTION': {'@CLE': '7545284', 'TYPECOLLEC...",NaN,IPTV_E122842004.jpg,NaN,"Vendredi, tout est permis avec Arthur"
27,167439778,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '0', 'CLAIR': ...",1,2017-12-02T01:35:00,5,"{'@CLEEMI': '122842678', '@DATEMODIF': '2017-1...",Tirage de l'Euro Millions,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '1083', '@GENRESIMPLE': 'Jeu', '#text...",NaN,NaN,"{'COLLECTION': {'@CLE': '5850858', 'TYPECOLLEC...",NaN,IPTV_C122842678.jpg,NaN,Tirage de l'Euro Millions
28,167439779,2017-11-07T12:08:13,"{'PT1': '0', 'PT2': '0', 'PT3': '1', 'CLAIR': ...",0,2017-12-02T01:40:00,290,"{'@CLEEMI': '108980346', '@DATEMODIF': '2017-1...",Programmes de la nuit,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '1057', '@GENRESIMPLE': 'Programme in...",NaN,NaN,None,NaN,NaN,NaN,Programmes de la nuit

In [69]:
data = data.drop(['ATTRIBUTS','EMISSION'],axis = 1)
data

,@CLEDIF,@DATEMODIF,CSA,DATEHEURE,DUREE,TITRE,PT1,PT2,PT3,CLAIR,...,FILMTELEFILM,FORMAT,GENRE,LESPERSONNES,LESTEXTES,MAGAZINEXY,NATIONALITE,PHOTO,SERIE,TITREEMISSION
0,167439753,2017-11-08T02:12:33,1,2017-12-01T06:25:00,120,TFou,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '403', '@GENRESIMPLE': 'Magazine jeun...",NaN,"{'TEXTE': [{'@TYPE': '0', 'LETEXTE': 'Au somma...","{'COLLECTION': {'@CLE': '6999', 'TYPECOLLECTIO...",NaN,IPTV_C122835453.jpg,NaN,TFou
1,167439754,2017-11-07T12:08:12,1,2017-12-01T08:25:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842665.jpg,NaN,MÃ©tÃ©o
2,167439755,2017-11-07T12:08:12,1,2017-12-01T08:30:00,45,TÃ©lÃ©shopping,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '425', '@GENRESIMPLE': 'Magazine de s...","{'PERSONNE': [{'@CLE': '120137', 'FONCTION': '...",NaN,"{'COLLECTION': {'@CLE': '6986', 'TYPECOLLECTIO...",NaN,IPTV_C122842666.jpg,NaN,TÃ©lÃ©shopping
3,167439756,2017-11-07T12:08:12,1,2017-12-01T09:15:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842667.jpg,NaN,MÃ©tÃ©o
4,167439757,2017-11-07T12:08:12,1,2017-12-01T09:20:00,30,Petits secrets entre voisins,0,0,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...",NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins
5,167439758,2017-11-07T12:08:12,1,2017-12-01T09:50:00,35,Petits secrets entre voisins,0,0,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...",NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins
6,167439759,2017-11-07T12:08:12,1,2017-12-01T10:25:00,35,Demain nous appartient,0,0,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '969', '@GENRESIMPLE': 'SÃ©rie dramati...","{'PERSONNE': [{'@CLE': '159285', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Maxime ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122835415.jpg,"{'COLLECTION': [{'@CLE': '26743151', 'TYPECOLL...",Demain nous appartient
7,167439760,2017-11-18T03:16:26,1,2017-12-01T11:00:00,55,Les feux de l'amour,0,0,0,0,...,NaN,"{'@CLE': '4', '#text': 'Feuilleton'}","{'@CLE': '50', '@GENRESIMPLE': 'SÃ©rie sentimen...","{'PERSONNE': [{'@CLE': '262561', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Jack es...",NaN,"{'@CLE': '7', 'PAYS': 'Etats-Unis', 'LIBELLE':...",IPTV_C120971283.jpg,"{'COLLECTION': [{'@CLE': '6475', 'TYPECOLLECTI...",Les feux de l'amour
8,167439761,2017-11-07T12:08:12,1,2017-12-01T11:55:00,5,Petits plats en Ã©quilibre,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '397', '@GENRESIMPLE': 'Magazine de l...","{'PERSONNE': {'@CLE': '122485', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Toutes le...","{'COLLECTION': {'@CLE': '3166156', 'TYPECOLLEC...",NaN,IPTV_C122842668.jpg,NaN,Petits plats en Ã©quilibre
9,167439762,2017-11-07T12:08:12,1,2017-12-01T12:00:00,55,Les douze coups de midi,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '950', '@GENRESIMPLE': 'Jeu', '#text'...","{'PERSONNE': {'@CLE': '125961', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Chaque jo...","{'COLLECTION': {'@CLE': '4188704', 'TYPECOLLEC...",NaN,IPTV_C122842669.jpg,NaN,Les douze coups de midi
10,167439763,2017-11-07T12:08:12,1,2017-12-01T12:55:00,5,L'affiche du jour,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '424', '@GENRESIMPLE': 'Magazine spor...","{'PERSONNE': [{'@CLE': '600066', 'FONCTION': '...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Un consul...","{'COLLECTION': {'@CLE': '3201344', 'TYPECOLLEC...",NaN,IPTV_C122842670.jpg,NaN,L'affiche du jour
11,167439764,2017-11-07T12:08:12,1,2017-12-01T13:00:00,30,Journal,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '952', '@GENRESIMPLE': 'Journal', '#t...","{'PERSONNE': {'@CLE': '120966', 'FONCTION': 'P...",NaN,"{'COLLECTION': {'@CLE': '8310', 'TYPECOLLECTIO...",NaN,IPTV_C122842959.jpg,NaN,Journal
12,167439765,2017-11-07T12:08:12,1,2017-12-01T13:30:00,10,Petits plats en Ã©quilibre,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '397', '@GENRESIMPLE': 'Magazine de l...","{'PERSONNE': {'@CLE': '122485', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Toutes le...","{'COLLECTION': {'@CLE': '3166156', 'TYPECOLLEC...",NaN,IPTV_C122842671.jpg,NaN,Petits plats en Ã©quilibre
13,167439766,2017-11-07T12:08:12,1,2017-12-01T13:40:00,15,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842672.jpg,NaN,MÃ©tÃ©o
14,167439767,2017-11-07T12:08:12,1,2017-12-01T13:55:00,105,En cavale pour NoÃ«l,0,0,0,0,...,{'TITREORIGINAL': 'Debbie Macomber's Dashing T...,"{'@CLE': '2', '#text': 'TÃ©lÃ©film'}","{'@CLE': '340', '@GENRESIMPLE': 'TÃ©lÃ©film mÃ©lo...","{'PERSONNE': [{'@CLE': '14104', 'FONCTION': 'R...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'AprÃ¨s ...",NaN,"{'@CLE': '155', 'PAYS': 'Canada', 'LIBELLE': '...",IPTV_E111248282.jpg,NaN,En cavale pour NoÃ«l
15,167439768,2017-11-07T12:08:12,1,2017-12-01T15:40:00,90,MariÃ© avant NoÃ«l,0,0,0,0,...,"{'TITREORIGINAL': 'A Bride for Christmas', 'AN...","{'@CLE': '2', '#text': 'TÃ©lÃ©film'}","{'@CLE': '340', '@GENRESIMPLE': 'TÃ©lÃ©film mÃ©lo...","{'PERSONNE': [{'@CLE': '488065', 'FONCTION': '...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'Deux c...",NaN,"{'@CLE': '16', 'PAYS': 'Etats-Unis - Canada', ...",IPTV_E71508277.jpg,NaN,MariÃ© avant NoÃ«l
16,167439769,2017-11-07T12:08:12,1,2017-12-01T17:10:00,65,Quatre mariages pour une lune de miel,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '967', '@GENRESIMPLE': 'TÃ©lÃ©rÃ©alitÃ©',...",NaN,"{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Quatre je...","{'COLLECTION': {'@CLE': '6774593', 'TYPECOLLEC...",NaN,IPTV_C122842673.jpg,NaN,Quatre mariages pour une lune de miel
17,167439770,2017-11-07T12:08:13,1,2017-12-01T18:15:00,65,Mon plus beau NoÃ«l,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '967', '@GENRESIMPLE': 'TÃ©lÃ©rÃ©alitÃ©',...","{'PERSONNE': {'@CLE': '365103', 'FONCTION': 'P...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Quatre fa...","{'COLLECTION': {'@CLE': '28892992', 'TYPECOLLE...",NaN,IPTV_C122843237.jpg,NaN,Mon plus beau NoÃ«l
18,167439771,2017-11-18T03:16:52,1,2017-12-01T19:20:00,35,Demain nous appartient,0,0,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '969', '@GENRESIMPLE': 'SÃ©rie dramati...","{'PERSONNE': [{'@CLE': '159285', 'FONCTION': '...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Rafael ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122835416.jpg,"{'COLLECTION': [{'@CLE': '26743151', 'TYPECOLL...",Demain nous appartient
19,167439772,2017-11-07T12:08:13,1,2017-12-01T19:55:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842674.jpg,NaN,MÃ©tÃ©o
20,167439773,2017-11-07T12:08:13,1,2017-12-01T20:00:00,35,Journal,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '952', '@GENRESIMPLE': 'Journal', '#t...","{'PERSONNE': {'@CLE': '333079', 'FONCTION': 'P...",NaN,"{'COLLECTION': {'@CLE': '8310', 'TYPECOLLECTIO...",NaN,IPTV_C122842950.jpg,NaN,Journal
21,167439774,2017-11-07T12:08:13,1,2017-12-01T20:35:00,5,My Million,0,0,0,0,...,NaN,"{'@CLE': '12', '#text': 'Magazine'}","{'@CLE': '421', '@GENRESIMPLE': 'Magazine de s...",NaN,NaN,"{'COLLECTION': {'@CLE': '12577694', 'TYPECOLLE...",NaN,IPTV_C122842675.jpg,NaN,My Million
22,167439775,2017-11-07T12:08:13,1,2017-12-01T20:40:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842676.jpg,NaN,MÃ©tÃ©o
23,167439776,2017-11-07T12:08:13,1,2017-12-01T20:45:00,5,Nos chers voisins,0,0,0,0,...,NaN,"{'@CLE': '3', '#text': 'SÃ©rie'}","{'@CLE': '31', '@GENRESIMPLE': 'SÃ©rie humorist...","{'PERSONNE': [{'@CLE': '2006', 'FONCTION': 'Ac...","{'TEXTE': [{'@TYPE': '101', 'LETEXTE': 'ProblÃ¨...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C122843067.jpg,"{'COLLECTION': [{'@CLE': '8555721', 'TYPECOLLE...",Nos chers voisins
24,167439777,2017-11-07T12:08:13,1,2017-12-01T20:50:00,10,C'est Canteloup,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '957', '@GENRESIMPLE': 'Divertissemen...","{'PERSONNE': [{'@CLE': '142528', 'FONCTION': '...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'DÃ©tournem...","{'COLLECTION': {'@CLE': '11736233', 'TYPECOLLE...",NaN,IPTV_C122842677.jpg,NaN,C'est Canteloup
25,167437456,2017-11-18T03:16:58,1,2017-12-01T21:00:00,150,EnfoirÃ©s Kids,1,0,0,0,...,NaN,"{'@CLE': '7', '#text': 'Concert'}","{'@CLE': '75', '@GENRESIMPLE': 'Concert', '#te...","{'PERSONNE': [{'@CLE': '1340672', 'FONCTION': ...","{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'Sur la ...",NaN,NaN,IPTV_E122841996.jpg,NaN,EnfoirÃ©s Kids
26,167437457,2017-11-07T12:08:13,1,2017-12-01T23:30:00,125,"Vendredi, tout est permis avec Arthur",0,1,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '932', '@GENRESIMPLE': 'Divertissemen...","{'PERSONNE': {'@CLE': '9021', 'FONCTION': 'PrÃ©...","{'TEXTE': {'@TYPE': '0', 'LETEXTE': 'Comme tou...","{'COLLECTION': {'@CLE': '7545284', 'TYPECOLLEC...",NaN,IPTV_E122842004.jpg,NaN,"Vendredi, tout est permis avec Arthur"
27,167439778,2017-11-07T12:08:13,1,2017-12-02T01:35:00,5,Tirage de l'Euro Millions,0,0,0,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '1083', '@GENRESIMPLE': 'Jeu', '#text...",NaN,NaN,"{'COLLECTION': {'@CLE': '5850858', 'TYPECOLLEC...",NaN,IPTV_C122842678.jpg,NaN,Tirage de l'Euro Millions
28,167439779,2017-11-07T12:08:13,0,2017-12-02T01:40:00,290,Programmes de la nuit,0,0,1,0,...,NaN,"{'@CLE': '16', '#text': 'Autre'}","{'@CLE': '1057', '@GENRESIMPLE': 'Programme in...",NaN,NaN,None,NaN,NaN,NaN,Programmes de la nuit

In [75]:
temp_data = pd.DataFrame()   
for i in range(29):    
    df = data['FORMAT']
    l = (df[[i]].values)[0]
    df2 = pd.DataFrame.from_dict(l,orient = 'index')
    df2 = df2.rename(columns = {0: i})
    #print(df2.head())
    temp_data = [temp_data,df2]
    temp_data = pd.concat(temp_data,axis = 1)
    temp_data = temp_data.drop(['#text'])
    temp_data = temp_data.T.rename(columns={"@CLE": "CLE-FORMAT"})
temp_data.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
@CLE,12,16,12,16,3,3,3,4,12,16,...,16,16,12,16,3,16,7,16,16,16

In [76]:
data = data.join(temp_data)
data = data.drop(['FORMAT'],axis=1)
data.head()

,@CLEDIF,@DATEMODIF,CSA,DATEHEURE,DUREE,TITRE,PT1,PT2,PT3,CLAIR,...,FILMTELEFILM,GENRE,LESPERSONNES,LESTEXTES,MAGAZINEXY,NATIONALITE,PHOTO,SERIE,TITREEMISSION,@CLE
0,167439753,2017-11-08T02:12:33,1,2017-12-01T06:25:00,120,TFou,0,0,0,0,...,NaN,"{'@CLE': '403', '@GENRESIMPLE': 'Magazine jeun...",NaN,"{'TEXTE': [{'@TYPE': '0', 'LETEXTE': 'Au somma...","{'COLLECTION': {'@CLE': '6999', 'TYPECOLLECTIO...",NaN,IPTV_C122835453.jpg,NaN,TFou,12
1,167439754,2017-11-07T12:08:12,1,2017-12-01T08:25:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842665.jpg,NaN,MÃ©tÃ©o,16
2,167439755,2017-11-07T12:08:12,1,2017-12-01T08:30:00,45,TÃ©lÃ©shopping,0,0,0,0,...,NaN,"{'@CLE': '425', '@GENRESIMPLE': 'Magazine de s...","{'PERSONNE': [{'@CLE': '120137', 'FONCTION': '...",NaN,"{'COLLECTION': {'@CLE': '6986', 'TYPECOLLECTIO...",NaN,IPTV_C122842666.jpg,NaN,TÃ©lÃ©shopping,12
3,167439756,2017-11-07T12:08:12,1,2017-12-01T09:15:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,"{'@CLE': '951', '@GENRESIMPLE': 'MÃ©tÃ©o', '#tex...",NaN,NaN,None,NaN,IPTV_C122842667.jpg,NaN,MÃ©tÃ©o,16
4,167439757,2017-11-07T12:08:12,1,2017-12-01T09:20:00,30,Petits secrets entre voisins,0,0,0,0,...,NaN,"{'@CLE': '1026', '@GENRESIMPLE': 'SÃ©rie sentim...",NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins,3

In [79]:
temp_data = pd.DataFrame()   
for i in range(29):    
    df = data['GENRE']
    l = (df[[i]].values)[0]
    df2 = pd.DataFrame.from_dict(l,orient = 'index')
    df2 = df2.rename(columns = {0: i})
    #print(df2.head())
    temp_data = [temp_data,df2]
    temp_data = pd.concat(temp_data,axis = 1)
    temp_data = temp_data.drop(['@GENRESIMPLE'])
temp_data = temp_data.T.rename(columns={"@CLE": "CLE-GENRE","#text":"description programme"})
temp_data.head()

    description programme CLE-GENRE
0       Magazine jeunesse       403
1                   MÃ©tÃ©o       951
2  Magazine de tÃ©lÃ©-achat       425
3                   MÃ©tÃ©o       951
4          SÃ©rie rÃ©aliste      1026

In [80]:
data = data.join(temp_data)
data = data.drop(['GENRE'],axis=1)
data.head()

,@CLEDIF,@DATEMODIF,CSA,DATEHEURE,DUREE,TITRE,PT1,PT2,PT3,CLAIR,...,LESPERSONNES,LESTEXTES,MAGAZINEXY,NATIONALITE,PHOTO,SERIE,TITREEMISSION,@CLE,description programme,CLE-GENRE
0,167439753,2017-11-08T02:12:33,1,2017-12-01T06:25:00,120,TFou,0,0,0,0,...,NaN,"{'TEXTE': [{'@TYPE': '0', 'LETEXTE': 'Au somma...","{'COLLECTION': {'@CLE': '6999', 'TYPECOLLECTIO...",NaN,IPTV_C122835453.jpg,NaN,TFou,12,Magazine jeunesse,403
1,167439754,2017-11-07T12:08:12,1,2017-12-01T08:25:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,NaN,None,NaN,IPTV_C122842665.jpg,NaN,MÃ©tÃ©o,16,MÃ©tÃ©o,951
2,167439755,2017-11-07T12:08:12,1,2017-12-01T08:30:00,45,TÃ©lÃ©shopping,0,0,0,0,...,"{'PERSONNE': [{'@CLE': '120137', 'FONCTION': '...",NaN,"{'COLLECTION': {'@CLE': '6986', 'TYPECOLLECTIO...",NaN,IPTV_C122842666.jpg,NaN,TÃ©lÃ©shopping,12,Magazine de tÃ©lÃ©-achat,425
3,167439756,2017-11-07T12:08:12,1,2017-12-01T09:15:00,5,MÃ©tÃ©o,0,0,0,0,...,NaN,NaN,None,NaN,IPTV_C122842667.jpg,NaN,MÃ©tÃ©o,16,MÃ©tÃ©o,951
4,167439757,2017-11-07T12:08:12,1,2017-12-01T09:20:00,30,Petits secrets entre voisins,0,0,0,0,...,NaN,"{'TEXTE': {'@TYPE': '102', 'LETEXTE': 'La vie ...",NaN,"{'@CLE': '349', 'PAYS': 'France', 'LIBELLE': '...",IPTV_C116093509.jpg,"{'COLLECTION': [{'@CLE': '10765454', 'TYPECOLL...",Petits secrets entre voisins,3,SÃ©rie rÃ©aliste,1026

In [81]:
data = data.drop(['LESPERSONNES','LESTEXTES','PHOTO'],axis=1)

In [84]:
data = data.drop(['MAGAZINEXY'],axis=1)

In [86]:
data = data.drop(['SERIE','NATIONALITE'],axis=1)

In [90]:
data = data.drop(['CS','FILMTELEFILM'],axis=1)

In [95]:
import pandas as pd
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
data['DATE'] = data['DATEHEURE'].apply(lambda x: x.split('T')[0])
data['HEURE'] = data['DATEHEURE'].apply(lambda x: x.split('T')[1])
data['minutes'] = data['HEURE'].apply(lambda x: int(x.split(':')[0])*60 + int(x.split(':')[1]))
data

      @CLEDIF           @DATEMODIF  CSA            DATEHEURE  DUREE                                  TITRE PT1 PT2 PT3 CLAIR DOLBY DOLBY51 STEREO RATIO STM VOST VM HD DIRECT DIFFERE RESUME PREMDIF DERDIF REDIF INEDIT_EN_CLAIR INEDIT_CRYPTE NOUVEAUTE TEMPSFORT OCCULTATIONMOBILE    @CLEEMI                          TITREEMISSION @CLE       description programme CLE-GENRE        DATE     HEURE  minutes
0   167439753  2017-11-08T02:12:33    1  2017-12-01T06:25:00    120                                   TFou   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               1             0         0         0                 0  122835453                                   TFou   12           Magazine jeunesse       403  2017-12-01  06:25:00      385
1   167439754  2017-11-07T12:08:12    1  2017-12-01T08:25:00      5                                  MÃ©tÃ©o   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842665                                  MÃ©tÃ©o   16                       MÃ©tÃ©o       951  2017-12-01  08:25:00      505
2   167439755  2017-11-07T12:08:12    1  2017-12-01T08:30:00     45                           TÃ©lÃ©shopping   0   0   0     0     0       0      1  16:9   0    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842666                           TÃ©lÃ©shopping   12      Magazine de tÃ©lÃ©-achat       425  2017-12-01  08:30:00      510
3   167439756  2017-11-07T12:08:12    1  2017-12-01T09:15:00      5                                  MÃ©tÃ©o   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842667                                  MÃ©tÃ©o   16                       MÃ©tÃ©o       951  2017-12-01  09:15:00      555
4   167439757  2017-11-07T12:08:12    1  2017-12-01T09:20:00     30           Petits secrets entre voisins   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     1               0             0         0         0                 0  116093509           Petits secrets entre voisins    3              SÃ©rie rÃ©aliste      1026  2017-12-01  09:20:00      560
5   167439758  2017-11-07T12:08:12    1  2017-12-01T09:50:00     35           Petits secrets entre voisins   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     1               0             0         0         0                 0  116093509           Petits secrets entre voisins    3              SÃ©rie rÃ©aliste      1026  2017-12-01  09:50:00      590
6   167439759  2017-11-07T12:08:12    1  2017-12-01T10:25:00     35                 Demain nous appartient   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     1               0             0         0         0                 0  122835415                 Demain nous appartient    3            SÃ©rie dramatique       969  2017-12-01  10:25:00      625
7   167439760  2017-11-18T03:16:26    1  2017-12-01T11:00:00     55                    Les feux de l'amour   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               1             0         0         0                 0  120971283                    Les feux de l'amour    4      Feuilleton sentimental        50  2017-12-01  11:00:00      660
8   167439761  2017-11-07T12:08:12    1  2017-12-01T11:55:00      5              Petits plats en Ã©quilibre   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842668              Petits plats en Ã©quilibre   12  Magazine de la gastronomie       397  2017-12-01  11:55:00      715
9   167439762  2017-11-07T12:08:12    1  2017-12-01T12:00:00     55                Les douze coups de midi   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842669                Les douze coups de midi   16                         Jeu       950  2017-12-01  12:00:00      720
10  167439763  2017-11-07T12:08:12    1  2017-12-01T12:55:00      5                      L'affiche du jour   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842670                      L'affiche du jour   12            Magazine sportif       424  2017-12-01  12:55:00      775
11  167439764  2017-11-07T12:08:12    1  2017-12-01T13:00:00     30                                Journal   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842959                                Journal   16                     Journal       952  2017-12-01  13:00:00      780
12  167439765  2017-11-07T12:08:12    1  2017-12-01T13:30:00     10              Petits plats en Ã©quilibre   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842671              Petits plats en Ã©quilibre   12  Magazine de la gastronomie       397  2017-12-01  13:30:00      810
13  167439766  2017-11-07T12:08:12    1  2017-12-01T13:40:00     15                                  MÃ©tÃ©o   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842672                                  MÃ©tÃ©o   16                       MÃ©tÃ©o       951  2017-12-01  13:40:00      820
14  167439767  2017-11-07T12:08:12    1  2017-12-01T13:55:00    105                    En cavale pour NoÃ«l   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  111248282                    En cavale pour NoÃ«l    2        TÃ©lÃ©film sentimental       340  2017-12-01  13:55:00      835
15  167439768  2017-11-07T12:08:12    1  2017-12-01T15:40:00     90                       MariÃ© avant NoÃ«l   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0   71508277                       MariÃ© avant NoÃ«l    2        TÃ©lÃ©film sentimental       340  2017-12-01  15:40:00      940
16  167439769  2017-11-07T12:08:12    1  2017-12-01T17:10:00     65  Quatre mariages pour une lune de miel   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842673  Quatre mariages pour une lune de miel   16                 TÃ©lÃ©rÃ©alitÃ©       967  2017-12-01  17:10:00     1030
17  167439770  2017-11-07T12:08:13    1  2017-12-01T18:15:00     65                     Mon plus beau NoÃ«l   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122843237                     Mon plus beau NoÃ«l   16                 TÃ©lÃ©rÃ©alitÃ©       967  2017-12-01  18:15:00     1095
18  167439771  2017-11-18T03:16:52    1  2017-12-01T19:20:00     35                 Demain nous appartient   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               1             0         0         0                 0  122835416                 Demain nous appartient    3            SÃ©rie dramatique       969  2017-12-01  19:20:00     1160
19  167439772  2017-11-07T12:08:13    1  2017-12-01T19:55:00      5                                  MÃ©tÃ©o   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842674                                  MÃ©tÃ©o   16                       MÃ©tÃ©o       951  2017-12-01  19:55:00     1195
20  167439773  2017-11-07T12:08:13    1  2017-12-01T20:00:00     35                                Journal   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842950                                Journal   16                     Journal       952  2017-12-01  20:00:00     1200
21  167439774  2017-11-07T12:08:13    1  2017-12-01T20:35:00      5                             My Million   0   0   0     0     0       0      1  16:9   1    0  0  1      1       0      0       0      0     0               0             0         0         0                 0  122842675                             My Million   12        Magazine de services       421  2017-12-01  20:35:00     1235
22  167439775  2017-11-07T12:08:13    1  2017-12-01T20:40:00      5                                  MÃ©tÃ©o   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842676                                  MÃ©tÃ©o   16                       MÃ©tÃ©o       951  2017-12-01  20:40:00     1240
23  167439776  2017-11-07T12:08:13    1  2017-12-01T20:45:00      5                      Nos chers voisins   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122843067                      Nos chers voisins    3          SÃ©rie humoristique        31  2017-12-01  20:45:00     1245
24  167439777  2017-11-07T12:08:13    1  2017-12-01T20:50:00     10                        C'est Canteloup   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842677                        C'est Canteloup   16       Divertissement-humour       957  2017-12-01  20:50:00     1250
25  167437456  2017-11-18T03:16:58    1  2017-12-01T21:00:00    150                          EnfoirÃ©s Kids   1   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               1             0         0         0                 0  122841996                          EnfoirÃ©s Kids    7                    VariÃ©tÃ©s        75  2017-12-01  21:00:00     1260
26  167437457  2017-11-07T12:08:13    1  2017-12-01T23:30:00    125  Vendredi, tout est permis avec Arthur   0   1   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842004  Vendredi, tout est permis avec Arthur   16              Divertissement       932  2017-12-01  23:30:00     1410
27  167439778  2017-11-07T12:08:13    1  2017-12-02T01:35:00      5              Tirage de l'Euro Millions   0   0   0     0     0       0      1  16:9   1    0  0  1      0       0      0       0      0     0               0             0         0         0                 0  122842678              Tirage de l'Euro Millions   16                     Loterie      1083  2017-12-02  01:35:00       95
28  167439779  2017-11-07T12:08:13    0  2017-12-02T01:40:00    290                  Programmes de la nuit   0   0   1     0     0       0      1  16:9   0    0  0  0      0       0      0       0      0     1               0             0         0         0                 0  108980346                  Programmes de la nuit   16       Programme indÃ©terminÃ©      1057  2017-12-02  01:40:00      100

In [83]:
temp_data = pd.DataFrame()   
for i in range(29):    
    df = data['MAGAZINEXY']
    l = (df[[i]].values)[0]
    df2 = pd.DataFrame.from_dict(l,orient = 'index')
    df2 = df2.rename(columns = {0: i})
    #print(df2.head())
    temp_data = [temp_data,df2]
    temp_data = pd.concat(temp_data,axis = 1)
temp_data.T.head()

TypeError: object of type 'NoneType' has no len()